### ISSUE TITLE
Breaks the measurement template

### ISSUE THREAD

**Issue by KevinRichard-GM** [Oromis/touch-vtt#9] opened 2020-12-27 21:33 UTC
I noticed measurement templates stopped working a few days ago and I just went through troubleshooting all the mods I have enabled and it appears to be TouchVTT. 

With TouchVTT enabled you can draw a template (say a 20' cone) but the effected squares don't show up and you can not interreact with the template or draw further templates till you refresh the screen, at which point the template disappears.

**Comment by Deuterazamus** [comment] 2020-12-29 11:02
Can confirm: with TouchVTT templates cannot be persisted on the map. 
Just wanted to add that you do not need to refresh the page to get rid of the inconsistent template but mouse right click also removes it.
Removing TouchVTT fixed the problem.

**Comment by Oromis** [comment] 2020-12-29 12:19
Thanks for reporting this, I just checked it but can't reproduce it. Could you maybe share a screenshot that shows the bug? Or do you have step-by-step instructions how I can reproduce it?

**Comment by Oromis** [comment] 2020-12-29 12:24
![image](https://user-images.githubusercontent.com/1381990/103283521-12f97000-49d9-11eb-812f-fe287138a626.png)

I just created these templates using touch controls... Seems to work fine.

**Comment by KevinRichard-GM** [comment] 2020-12-29 12:24
Could be a conflict with another module. I’ll disable all modules except
TouchVTT and see what happens.

-Kevin

**Comment by Deuterazamus** [comment] 2020-12-29 14:12
I've disabled all modules except for TouchVTT and nominal behaviour is restored. Adding back modules I've found that the template tools breaks when enabling both Easy Target and libWrapper. Active modules exported via TidyUI (tested neutral in this case):

easy-target--v2.10;
lib-wrapper--v1.0.5.3;
tidy-ui_game-settings--v0.1.21;
touch-vtt--v1.1.1;

Stacktrace:
![image](https://user-images.githubusercontent.com/68236513/103289723-25c77100-49e8-11eb-8437-6f9e9ae5934a.png)

**Comment by KevinRichard-GM** [comment] 2020-12-29 14:59
Confirmed, Easy Target module appears to be the culprit. Easy enough to
fix, say by by Easy Target.

**Comment by Oromis** [comment] 2020-12-29 18:26
Okay, from the stack trace it looks like an incompatibility. Both modules mess with the measurement layer. When I find the time I can take a look and see if I can do it in a way thats compatible with easy target

**Comment by Deuterazamus** [comment] 2020-12-29 18:32
Just please note that with Easy Target alone the bug does not happen, both libWrapper and Easy Target must be enabled to trigger the error. The same is also true with libWrapper alone.

**Comment by Oromis** [comment] 2021-01-02 12:11
Okay I took a look at the conflict and I think I can resolve it by switching to libWrapper. So in some future version, touch-vtt will also suggest the GM to use libWrapper as a dependency to resolve such conflicts. I just learned about libWrapper and it's a very nice project :)

**Comment by Oromis** [comment] 2021-01-02 13:10
Fixed in v1.2.2

**Closed by Oromis** 2021-01-02 13:10 UTC
