### ISSUE TITLE
Not activating window on dual screen setup

### ISSUE THREAD

**Issue by QuantumFunks** [Oromis/touch-vtt#17] opened 2021-03-23 06:16 UTC
Not sure if this is a Touch VTT issue or one associated with the windows touch environment but if i tap on Foundry whilst on another active window, on another monitor, it doesnt register. The circle that indicates where the touch input is appears on the display, but the mouse doesnt move to that spot and i cant move actors or activate any controls unless i move the mouse back over to chrome on the touch screen display and click on the chrome window. Alt+Tab doesnt work either. Unless i click the window, the touch controls dont register at all.

I have dual screen setup with a 32 inch monitor and a 50 inch TV built into a table that has a capacitive touch foil attached to a 6mm glass panel over the top.

**Comment by Oromis** [comment] 2021-04-25 15:45
Thanks for getting in touch and sorry for the long delay. 

I'm afraid I cannot reproduce this. When I activate another window and then touch anywhere on the Foundry VTT canvas, the FoundryVTT window is focused again and touch input works as expected. 

Can you give me more input on how to reproduce this? Which Browser do you use?

**Comment by Oromis** [comment] 2021-06-04 15:49
I'll close this for now, feel free to re-open if this is still an issue and you can provide instructions on how to reproduce it.

**Closed by Oromis** 2021-06-04 15:49 UTC
