### ISSUE TITLE
Drag and dropping a token directly after deselecting causes the camera to pan

### ISSUE THREAD

**Issue by watermelonwolverine** [Oromis/touch-vtt#87] opened 2024-08-11 20:21 UTC
Drag and dropping a token directly after deselecting it or other tokens (by tapping on an empty spot on the map) causes the camera to pan

**Comment by Aioros** [comment] 2024-08-13 13:54
I didn't seem to be able to reproduce this yet, but it might be fixed in v2.2.4. Let me know if the issue still persists after updating.

**Comment by watermelonwolverine** [comment] 2024-08-13 21:10
I updated to 2.2.4 and tried to replicate the issue. 
I have all extensions other than touch-vtt, force-client-settings and libwrapper disabled.

https://github.com/user-attachments/assets/76328a69-f7ff-48c0-9abd-b77411a01a74

**Comment by watermelonwolverine** [comment] 2024-08-13 21:26
I don't think it has anything to do with the deselect but with the tap I do to deselect the token.

**Comment by Aioros** [comment] 2024-08-13 21:29
Yeah, my impression is that the "deselect" touch gets kinda stuck for some reason, and when you tap again it goes into gesture mode. I imagine that this doesn't happen if you disable Zoom/Pan Gestures in the settings, right?

**Comment by watermelonwolverine** [comment] 2024-08-13 21:41
Actually, it does

**Comment by Aioros** [comment] 2024-08-13 21:45
Huh, interesting, thanks. I'll keep you posted.

**Comment by Aioros** [comment] 2024-08-14 13:20
I made some changes in the develop branch that might help with this. Could you try installing the latest unstable version and report back? I imagine you already know how, but in case you don't: at the bottom of the "Install Module" window, paste this manifest URL: [https://github.com/Oromis/touch-vtt/releases/download/v2.2.4-1-gadfbfd6/module.json](https://github.com/Oromis/touch-vtt/releases/download/v2.2.4-1-gadfbfd6/module.json)

**Comment by watermelonwolverine** [comment] 2024-08-14 16:18
Same behavior as far as I can tell. It happens with gestures enabled and without.
The attach debug log is with gestures disabled.

[debug-log.txt](https://github.com/user-attachments/files/16615931/debug-log.txt)

**Comment by Aioros** [comment] 2024-08-14 20:11
Alright, so, first of all let me know if I'm abusing your patience by asking you all this stuff every time. If you're up to it, I would like you to try again with [this latest unstable release](https://github.com/Oromis/touch-vtt/releases/download/v2.2.5-2-g11bea3a/module.json), and paste one of those nice giant logs again.

The behavior should not have changed, but I put some more useful info in the logs. Actually, there should be one change: in this version, I expect at least the panning not to happen when the gestures are disabled. Let me know, and thanks again for your assistance.

**Comment by watermelonwolverine** [comment] 2024-08-14 21:53
No problem, I still have patience left. Thank you, on the other hand, for taking the time to investigate this issue.

The behavior is still the same, even with gestures disabled. I noticed that selecting a token and then deselecting by tapping anywhere causes the camera to pan when I move the normal mouse pointer. Also, every tap I do now places a ping, even the shortest ones I can manage, which wasn't the case before. Is this the intended behavior? 
I would guess that this indicates that both right and left mouse buttons somehow got stuck?

[select_token_deselect_token_drag_token.txt](https://github.com/user-attachments/files/16619299/select_token_deselect_token_drag_token.txt)

[select_token_deselect_token.txt](https://github.com/user-attachments/files/16619301/select_token_deselect_token.txt)

[touch_down_touch_up.txt](https://github.com/user-attachments/files/16619302/touch_down_touch_up.txt)

**Comment by Aioros** [comment] 2024-08-14 22:08
Yeah, it's not intended and you have the right idea. Basically, whenever you touch the canvas we start two timers: a 1s one before we send a ping, and a 400ms one before we send a right click (the right click opens the token hud on a token, and starts panning the canvas until you release). Normally, these timers are reset when anything else happens (like releasing the touch), but something is preventing it in your case.

I'll keep investigating and report back, thanks again.

**Comment by Aioros** [comment] 2024-08-15 15:43
The new v2.2.6 should (and I'll keep it as "should" for now) fix this, and potentially #83 too. Could you try it out and let me know if it does?

**Comment by watermelonwolverine** [comment] 2024-08-15 16:59
I can't replicate it with 2.2.6 so this seems to be fixed

**Closed** 2024-08-15 17:12 UTC
