### ISSUE TITLE
Can't drag through doors

### ISSUE THREAD

**Issue by ElvishJerricco** [Oromis/touch-vtt#22] opened 2021-05-25 20:40 UTC
I can't seem to drag a token through an open door with this module.

**Comment by Oromis** [comment] 2021-06-01 08:41
Hm, I cannot reproduce this. Even if the door isn't aligned perfectly with the grid I have no issues dragging a token through a door. 

Can you provide more details on how to reproduce this problem? Could you disable other modules to check if another module interferes here?

**Comment by Oromis** [comment] 2021-07-18 12:00
Cannot reproduce => I'll close it.

**Closed by Oromis** 2021-07-18 12:00 UTC
