### ISSUE TITLE
Touching token open player sheet

### ISSUE THREAD

**Issue by raremind1071** [Oromis/touch-vtt#62] opened 2023-07-05 13:40 UTC

**Comment by patrickmohrmann** [comment] 2023-09-10 22:17
I agree, it would be great to have an option not to do so that would make game play much easier

**Comment by hiszpek** [comment] 2023-09-18 15:57
I found a way for this to work, but it requires modifying the game files manually https://github.com/Oromis/touch-vtt/issues/61#issuecomment-1723727061

**Comment by Aioros** [comment] 2024-06-21 14:25
Closing as duplicate of #61

**Closed by Aioros** 2024-06-21 14:25 UTC
