### ISSUE TITLE
Zoom/pan gestures work only once

### ISSUE THREAD

**Issue by rzhikharevich** [Oromis/touch-vtt#68] opened 2024-06-25 15:51 UTC
After opening Foundry I can use either of the gestures but only once. After that multi-touches seem to be registered individually, e.g. pinching creates selection rectangles with one point of the rectangle jumping between both fingers.

Foundry version: 12.327 (stable)
Device: a touch-enabled Windows 11 tablet/laptop hybrid (Minisforum V3)
Browser: Chrome / Firefox

Additionally, the module seemed to work perfectly in Foundry v11.315 (at least with the three-finger panning option; two-finger panning was very jittery).

**Comment by rzhikharevich** [comment] 2024-06-26 23:15
Enabling the Touch Events API with `--touch-events` seems to fix this for me. Maybe something is wrong with the event filtering logic (i.e. `isTouchEvent` and `shouldHandleEvent`) when the Pointer API is used?

cc @Aioros

**Comment by Aioros** [comment] 2024-06-26 23:22
Interesting. Thanks for all the info, I'll look into it.

**Comment by Aioros** [comment] 2024-07-01 14:31
Hey, so I just deployed v2.0.0, which has a significant overhaul in the basic functionality of the module. Any chance you could let me know if the issue is still there for you after updating?

**Comment by rzhikharevich** [comment] 2024-07-03 14:54
@Aioros Hi, the latest version seems to work for me without my workaround. Thank you for your efforts!

**Comment by Aioros** [comment] 2024-07-03 14:58
Awesome, thanks for the feedback! I'll close this issue, feel free to open a new one if it still happens in other environments.

**Closed by Aioros** 2024-07-03 14:58 UTC
Labels: needs update
