### ISSUE TITLE
Attack & Damage widget check

### ISSUE THREAD

**Issue by Zarhog** [Oromis/touch-vtt#8] opened 2020-12-20 10:59 UTC
when clicking on dmg & attack roll widget the confirmation window dosnt show
![131925228_1165391297226711_1295554644455557473_n](https://user-images.githubusercontent.com/76391362/102711544-5dc90880-42b2-11eb-9397-9da32e58cf89.png)

also you should ass a UI Scale to this considering what its for

@media only screen and (max-width: 600px) {
  body > div {
    zoom: 0.5
  }
}

**Comment by Oromis** [comment] 2020-12-23 12:13
Thanks for reporting, I'll take a look

**Comment by Oromis** [comment] 2021-01-02 11:44
Hm, can't reproduce this. Could it be a module conflict? Please try by disabling other modules to see if the bug goes away and report back.

**Comment by Oromis** [comment] 2021-06-04 09:53
I'll close this as I cannot reproduce it. Feel free to re-open the issue if you can provide steps to reproduce.

**Closed by Oromis** 2021-06-04 09:53 UTC
